### ISSUE TITLE
The Pain of an ESM-only Module in a TypeScript Library Exporting CommonJS

### ISSUE THREAD

**Issue by jakobo** [jakobo/codedrift#105]
```yaml
---
slug: esm-only-typescript-commonjs
published: 2004-12-02T00:00:00-08:00
description: It's a corner case every library author will crash against, and it lacks a great solution, only workarounds.
changelog: ~
---
```

* Intro / Explain
  * taskless/graphinql and a few other libraries rely on `p-retry` and `serialize-error`
  * https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c
  * If the package is used in an async context, you could use [await import(…)](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import#dynamic_imports) from CommonJS instead of require(…)
* What the actual F is typescript doing
  * `const x = await import("...")` yields `Promise.resolve(require("..."))`
  * `const x = import("...") yields `require("...")`
  * Happens even when using `node16` or `nodenext` module resolution
  * As far as TypeScript is concerned, `import` is a dirty word
* Workarounds
  * A local CJS file that performs the `import` for you, telling TypeScript to bugger off
    * Requires some JSDoc shenanigans to properly type the export
  * Using eval to force TypeScript not to transform the module
    * It's... eval. 
    * Gets to stay in TypeScript

I've included both solutions below

```js
/**
 * @type {<T = unknown>(name: string) => T}
 */
const load = (id) => import(id);
module.exports = load;
module.exports.loadModule = load;
```

```ts
export const load = async <T = unknown>(name: string) => {
  return Promise.resolve((0, eval)(`import("${name}")`) as T);
};
```
