### ISSUE TITLE
In Memoriam

### ISSUE THREAD

**Issue by jakobo** [jakobo/codedrift#13]
```yaml
---
slug: in-memoriam
published: 2014-06-11T00:00:00.000Z
description: For Eric, For Kat, For the Meyerses
changelog:
  2020-02-23: This was rescued from the archives of the old [felocity.org](https://web.archive.org/web/20050507121849/http://www.felocity.org/journal). As a result, many links in this piece were left pointing to archive.org destinations.
  2020-02-24: Also, fuck cancer.
theme:
  primary: "#663399"
---
```

I have conversed with Eric Meyer twice in my life. The first time was an oddball question on his reset.css file. The second was in person at my first ever An Event Apart. In only two conversations, the haze surrounding CSS and specificity was removed and I finally saw a beautiful web. He doesn't know it, but those two conversations were when my career moved away from server code in favor of the browser. For many of us in the web industry, Eric is a mentor and an inspiration.

Since the middle of last year, Eric and his wife Kat have shared with the world [a parents' nightmare: their battle with cancer](https://web.archive.org/web/20141009223744/http://meyerweb.com/eric/thoughts/category/personal/cancer). Their second child Rebecca was diagnosed in August with grade 3 (anaplastic) astrocytoma. Day by day we watched, hoped, and prayed for their daughter to win a battle that wasn't of her choosing.

Rebecca Alison Meyer passed away June 7, 2014. She was six years, eleven and a half hours old.

On June 12 and days after, [the internet will be awash in purple](https://web.archive.org/web/20141009223744/http://www.zeldman.com/2014/06/10/the-color-purple/). The color #663399 to be exact. For those of us who the Meyer family has touched deeply, it is our symbol of mourning. This page, all the tweets, and all that will be said in person and online cannot begin express the collective sadness we all share. Eric and family, may the pages, the blogs, [the tweets](https://web.archive.org/web/20141009223744/https://twitter.com/search?f=realtime&amp;q=%23663399Becca), and the comments all find you. I wish the best for you all as you make it through the the days to come.

---

[The family requests charitable donations](https://web.archive.org/web/20141009223744/http://meyerweb.com/eric/thoughts/2014/06/09/in-memoriam-2/) be made in Rebecca's name to the Philadelphia Ronald McDonald House or the St. Baldrick's Foundation.
